        [toolchain]
        anchor_version = "0.29.0"
[features]
seeds = false
skip-lint = false

[programs.localnet]
pumpwithfriens = "cAQ5uztwVrNw7Us1GbCLmsdSdQtUmwtS23mj9y5hhXy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
