[workspace]
members = [
    "programs/*"
]
[profile.release]
overflow-checks = true
lto = "thin"
codegen-units = 1
[profile.release.build-override]
opt-level = "z"
incremental = false
codegen-units = 1
